# -*- coding: utf-8 -*-
"""AgTech_Data_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UT2GxhUpuv56iNBJsG9u_jz8oMfFORqW
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Lock seed for stable, realistic data generation
np.random.seed(101)

records = 1000
start_date = datetime(2025, 1, 1)
crops = ['Wheat', 'Maize', 'Soybeans', 'Cotton']
regions = ['North Zone', 'East Valley', 'South Plains', 'West Delta']
fertilizers = ['Organic Compost', 'NPK Blend', 'Ammonium Nitrate', 'None']

data = []

for i in range(records):
    date = start_date + timedelta(days=int(np.random.randint(0, 365)))
    crop = np.random.choice(crops)
    region = np.random.choice(regions)
    fertilizer = np.random.choice(fertilizers)

    # 1. Weather & IoT Telemetry Layer
    base_temp = 22 if region == 'South Plains' else 28
    temperature = float(np.random.normal(base_temp, 4))

    base_rainfall = 45 if region == 'East Valley' else 30
    rainfall = float(np.random.normal(base_rainfall, 8))
    rainfall = max(5.0, rainfall)

    soil_moisture = float(np.clip(np.random.normal(rainfall * 1.1 + 22, 6), 15, 85))

    # 2. Pesticide Operations Layer
    base_pesticide = 14 if crop == 'Cotton' else 6
    pesticide_usage = float(max(1.0, np.random.normal(base_pesticide, 2)))

    # 3. Core Analytics Engine (Yield & Financials)
    pest_factor = 1.15 if (4 < pesticide_usage < 16) else 0.75
    fert_multiplier = 1.35 if fertilizer == 'NPK Blend' else (0.85 if fertilizer == 'None' else 1.1)

    base_yield = 4.5 if crop == 'Maize' else 2.9
    yield_tons = float(max(1.0, np.random.normal(base_yield * fert_multiplier * pest_factor, 0.4)))

    # Financial Market Constants
    price_per_ton = {'Wheat': 240, 'Maize': 180, 'Soybeans': 420, 'Cotton': 650}[crop]
    gross_revenue = yield_tons * price_per_ton
    cost_per_acre = float(np.random.normal(380, 25) + (130 if fertilizer != 'None' else 0) + (pesticide_usage * 12))
    net_profit = float(gross_revenue - cost_per_acre)

    data.append([date, crop, region, soil_moisture, rainfall, temperature, pesticide_usage, yield_tons, net_profit, fertilizer])

columns = [
    'Date', 'Crop', 'Region', 'Soil_Moisture_Pct', 'Rainfall_mm',
    'Temperature_C', 'Pesticide_Usage_Kg', 'Yield_Tons', 'Net_Profit_USD', 'Fertilizer'
]

df = pd.DataFrame(data, columns=columns)
df.to_csv('agtech_perfect_data.csv', index=False)
print(" Flawless dataset generated! File name: 'agtech_perfect_data.csv'")